# PAM is split by responsibility under src/pam/. Keep this file as the public include point.
include("pam/2d/sources.jl")
include("pam/2d/config.jl")
include("pam/2d/medium.jl")
include("pam/2d/reconstruction.jl")
include("pam/2d/analysis.jl")
include("pam/2d/workflow.jl")
include("pam/2d/sweep.jl")
include("pam/3d/sources3d.jl")
include("pam/3d/config3d.jl")
include("pam/3d/medium3d.jl")
include("pam/3d/reconstruction3d.jl")
include("pam/3d/analysis3d.jl")
include("pam/setup/config.jl")
include("pam/setup/sources.jl")
include("pam/setup/medium.jl")
include("common/kwave_wrapper.jl")
